WIP: Adds Cashtoken support
pybitcash/bitcash pull request #122
Opened 2023-03-04 14:44 UTC by yashasvi-ranawat

Builds on #119 

Adds Cashtoken support to Bitcash.

- [x] Unspent are aware of cashtoken
- [x] Cashtoken handling class
- [x] Sanitized outputs are aware of cashtokens
- [ ] wallets are aware of cashtokens
- [ ] wallets can generate cashtoken tx
- [ ] wallets can generate cashtokens

2023-03-23 14:47 UTC, yashasvi-ranawat commented
@merc1er I realised the CashToken spec has test vectors too, added them as well. Its ready for review.
The final thing left is to update the CASHTOKEN_ACTIVATION_BLOCKHEIGHT to the block after 1684152000 MTP.

2023-05-12 13:11 UTC, yashasvi-ranawat commented
This Cashtoken pull request is designed with the assumption that the utxo query from the BitcoinDotComAPI will fetch scriptcodes with attached token prefix.
However, while adding refactoring PATFO check to the BitcoinDotComAPI, I realised the API sends only the locking script for all utxos (which makes sense). This implies that any token prefix attached to individual utxo might be missed.
Therefore, this pull request is dependant on https://devsuite.actorforth.org/ on adding Cashtoken support.

2023-06-10 15:15 UTC, merc1er commented
@yashasvi-ranawat: Does the CashToken sections shows for you in the index page of the docs? I tried building locally (`cd docs; make html`) but I am not seeing anything about tokens.

2023-06-11 06:21 UTC, yashasvi-ranawat commented
> @yashasvi-ranawat: Does the CashToken sections shows for you in the index page of the docs? I tried building locally (`cd docs; make html`) but I am not seeing anything about tokens.

Yes. I checked the changelog on this pull request, I do see the doc changes that should add it to the index page.

2023-07-15 12:02 UTC, merc1er requested changes
Outstanding work!

Thanks a lot for both fixing the UTXO issue and implementing the Cash Token feature at the same time!

As discussed, I left a comment on the address format. I also left a couple very minor comments.

2023-07-16 18:16 UTC, yashasvi-ranawat commented on docs/source/guide/cashtokens.rst
> +the version which do not signal cashaddress.
Added key.cashtoken_address

2023-07-16 18:17 UTC, yashasvi-ranawat commented on bitcash/transaction.py
> +            token_prefix = b""
Wrongly thought binary is mutable in python :/

2023-07-16 18:17 UTC, yashasvi-ranawat commented on bitcash/network/APIs/BitcoinDotComAPI.py
> +        address = cashtokenaddress_to_address(address)
Changed the CashAddr format, however still left the function.

2023-07-17 03:50 UTC, merc1er approved these changes
I'm very impressed with the quality of your work. Everything that I tested worked flawlessly.

Thank you for this major contribution!

Could you please confirm that there no longer is anything not backwards compatible in this PR?

2023-07-17 03:53 UTC, merc1er commented
Also if you don't mind I'll add you to the `AUTHORS.md` file as a contributor.

2023-07-17 05:19 UTC, merged

2023-07-17 05:39 UTC, merc1er commented
For some reason tests won't pass on Python 3.7. That's not much of an issue (Python 3.7 was released over 5 years ago), but could you confirm we no longer support 3.7 with the newest changes?

If so I'll remove it in favor of 3.11, and release version `1.0.0` of BitCash.

2023-07-17 06:15 UTC, yashasvi-ranawat commented
> Could you please confirm that there no longer is anything not backwards compatible in this PR?

I tested with pre-merge tests, wallet and cashaddress are backwards compatible. The sanitised output format has been changed, so no backwards compatibility in the transactions.py. However, those I think are not directly used by any user, but via wallet.py. The old output (the one user makes, not the sanitised output) format still works.

> For some reason tests won't pass on Python 3.7. That's not much of an issue (Python 3.7 was released over 5 years ago), but could you confirm we no longer support 3.7 with the newest changes?

Python 3.7 is already at its [end-of-life](https://devguide.python.org/versions/)

2023-07-18 03:32 UTC, bitjson commented
@yashasvi-ranawat fantastic work, thanks for all you're doing on this library! Do you have a Twitter account I can follow/highlight?

2023-07-18 06:18 UTC, yashasvi-ranawat commented
@bitjson Thanks a lot. My twitter handle: https://twitter.com/yashasviranawat